# Generated by Django 4.2.27 on 2026-01-28 11:10

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "order status history",
                "verbose_name_plural": "order status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.JSONField(default=dict, verbose_name="billing address"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="delivered at"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="estimated delivery"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="guest phone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="payment method"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_transaction_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="transaction ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="promo code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="shipped at"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(default=dict, verbose_name="shipping address"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="shipping method"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="tracking number"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="download_url",
            field=models.URLField(blank=True, verbose_name="download URL"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_digital",
            field=models.BooleanField(default=False, verbose_name="digital product"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="license_key",
            field=models.TextField(blank=True, verbose_name="license key"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(blank=True, verbose_name="product image URL"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=apps.orders.models.generate_order_number,
                max_length=50,
                unique=True,
                verbose_name="order number",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="orders_orde_user_id_37fed6_idx"
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.order",
                verbose_name="order",
            ),
        ),
    ]
