# Generated by Django 4.2.27 on 2026-01-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "min_delivery_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="min delivery days"
                    ),
                ),
                (
                    "max_delivery_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="max delivery days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "free_above",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Free shipping for orders above this amount",
                        max_digits=10,
                        null=True,
                        verbose_name="free above amount",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "shipping method",
                "verbose_name_plural": "shipping methods",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=100, verbose_name="session key"),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("shipping", "Shipping"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                        ],
                        default="address",
                        max_length=20,
                        verbose_name="current step",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="guest email"
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="guest phone"
                    ),
                ),
                (
                    "guest_shipping_address",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="guest shipping address"
                    ),
                ),
                (
                    "guest_billing_address",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="guest billing address"
                    ),
                ),
                (
                    "same_as_shipping",
                    models.BooleanField(
                        default=True, verbose_name="billing same as shipping"
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="promo code"
                    ),
                ),
                (
                    "customer_note",
                    models.TextField(blank=True, verbose_name="customer note"),
                ),
                (
                    "cart_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="cart data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_checkout_sessions",
                        to="accounts.address",
                        verbose_name="billing address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_checkout_sessions",
                        to="accounts.address",
                        verbose_name="shipping address",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="checkout.shippingmethod",
                        verbose_name="shipping method",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "checkout session",
                "verbose_name_plural": "checkout sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
