# Generated by Django 4.2.27 on 2026-01-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="payment method"
            ),
        ),
    ]
