# Generated by Django 4.2.27 on 2026-01-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="rate (%)",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Bangladesh",
                        max_length=100,
                        verbose_name="country",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default"),
                ),
            ],
            options={
                "verbose_name": "tax class",
                "verbose_name_plural": "tax classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("BDT", "Bangladeshi Taka"), ("USD", "US Dollar")],
                        default="BDT",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum retail price",
                        max_digits=12,
                        verbose_name="list price (MRP)",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Special sale price (leave blank if not on sale)",
                        max_digits=12,
                        null=True,
                        verbose_name="sale price",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase/cost price (for internal use)",
                        max_digits=12,
                        null=True,
                        verbose_name="cost price",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices",
                        to="pricing.taxclass",
                        verbose_name="tax class",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "price",
                "verbose_name_plural": "prices",
            },
        ),
    ]
