# Generated by Django 4.2.27 on 2026-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="subtitle"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="button text"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="button link"
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("primary", "Primary (Dark Blue)"),
                            ("secondary", "Secondary (Orange)"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("outline-light", "Outline Light"),
                        ],
                        default="secondary",
                        max_length=20,
                        verbose_name="button style",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="linear-gradient(135deg, #003366 0%, #0054A6 100%)",
                        help_text="CSS color or gradient value",
                        max_length=200,
                        verbose_name="background color/gradient",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="slides/",
                        verbose_name="background image",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-laptop)",
                        max_length=50,
                        verbose_name="icon class",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="badge text"
                    ),
                ),
                (
                    "badge_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("success", "Success"),
                            ("danger", "Danger"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="secondary",
                        max_length=20,
                        verbose_name="badge style",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "hero slide",
                "verbose_name_plural": "hero slides",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionalBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="button text"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="button link"
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="button style",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="badge text"
                    ),
                ),
                (
                    "badge_style",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("success", "Success"),
                            ("danger", "Danger"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="secondary",
                        max_length=20,
                        verbose_name="badge style",
                    ),
                ),
                (
                    "background_style",
                    models.CharField(
                        default="linear-gradient(135deg, #003366 0%, #0054A6 100%)",
                        help_text="CSS color or gradient value",
                        max_length=200,
                        verbose_name="background style",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/",
                        verbose_name="background image",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("full", "Full Width"),
                        ],
                        default="left",
                        max_length=10,
                        verbose_name="position",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "promotional banner",
                "verbose_name_plural": "promotional banners",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
