# Generated by Django 4.2.27 on 2026-02-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("shipping", "Shipping & Delivery"),
                            ("payment", "Payment"),
                            ("returns", "Returns & Refunds"),
                            ("account", "Account"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ item",
                "verbose_name_plural": "FAQ items",
                "ordering": ["category", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "subtitle",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="subtitle"
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("products", "Featured Products"),
                            ("categories", "Featured Categories"),
                            ("brands", "Featured Brands"),
                            ("custom", "Custom Content"),
                        ],
                        default="products",
                        max_length=20,
                        verbose_name="section type",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        default="#ffffff",
                        max_length=100,
                        verbose_name="background color",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[("dark", "Dark"), ("light", "Light")],
                        default="dark",
                        max_length=20,
                        verbose_name="text color",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "featured section",
                "verbose_name_plural": "featured sections",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FooterSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "footer section",
                "verbose_name_plural": "footer sections",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="DCL Ecommerce",
                        max_length=100,
                        verbose_name="site name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="tagline"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="logo"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="favicon"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="SEO title"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="SEO description"
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO keywords"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter/X URL"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="YouTube URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Copyright text for footer",
                        verbose_name="footer text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="customer name"),
                ),
                (
                    "customer_title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="title/location"
                    ),
                ),
                (
                    "customer_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="customer image",
                    ),
                ),
                ("content", models.TextField(verbose_name="testimonial content")),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        default=5,
                        verbose_name="rating",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "testimonial",
                "verbose_name_plural": "testimonials",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                (
                    "open_in_new_tab",
                    models.BooleanField(default=False, verbose_name="open in new tab"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="cms.footersection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
